### ISSUE TITLE
Offline_mi.py运行报错

### ISSUE THREAD

**Issue by USTC-V** [TBC-TJU/MetaBCI#39]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\joblib\externals\loky\process_executor.py", line 428, in _process_worker
    r = call_item()
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\joblib\externals\loky\process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\joblib\_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "<decorator-gen-605>", line 10, in _get_single_subject_data
  File "C:\Users\WTP\Desktop\MetaBCI-master\metabci\brainda\paradigms\base.py", line 195, in _get_single_subject_data
    data = dataset.get_data([subject_id])
  File "<decorator-gen-604>", line 12, in get_data
  File "C:\Users\WTP\Desktop\MetaBCI-master\metabci\brainda\datasets\base.py", line 169, in get_data
    data[subject] = self._get_single_subject_data(subject)
  File "C:\Users\WTP\Desktop\MetaBCI-master\demos\brainflow_demos\datasets.py", line 108, in _get_single_subject_data
    raw = read_raw_cnt(run_file,
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\mne\io\cnt\cnt.py", line 164, in read_raw_cnt
    return RawCNT(input_fname, eog=eog, misc=misc, ecg=ecg,
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\mne\io\cnt\cnt.py", line 393, in __init__
    info, cnt_info = _get_cnt_info(input_fname, eog, ecg, emg, misc,
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\mne\io\cnt\cnt.py", line 175, in _get_cnt_info
    with open(input_fname, 'rb', buffering=0) as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\WTP\\Desktop\\MetaBCI-master\\demos\\brainflow_demos\\data\\ssvep\\sub1\\1.cnt'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/WTP/Desktop/MetaBCI-master/demos/brainflow_demos/Offline_ssvep.py", line 299, in <module>
    X, y, meta = paradigm.get_data(
  File "<decorator-gen-606>", line 10, in get_data
  File "C:\Users\WTP\Desktop\MetaBCI-master\metabci\brainda\paradigms\base.py", line 377, in get_data
    *Parallel(n_jobs=n_jobs)(
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\joblib\parallel.py", line 1098, in __call__
    self.retrieve()
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\joblib\parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\site-packages\joblib\_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\concurrent\futures\_base.py", line 444, in result
    return self.__get_result()
  File "D:\ProgramData\Miniconda3\envs\psychopy\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\WTP\\Desktop\\MetaBCI-master\\demos\\brainflow_demos\\data\\ssvep\\sub1\\1.cnt'

**Comment by hanjiagaun** [comment]
你好，请问你解决了这个问题吗？我也遇到了这个问题，但不知道怎么解决

**Comment by USTC-V** [comment]
> 你好，请问你解决了这个问题吗？我也遇到了这个问题，但不知道怎么解决

是因为缺少数据集文件，不知道团队能否提供用于离线分析的cnt文件
